name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19'

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Set Environment Variables
      run: |
        echo "VITE_BACKEND_URL_PROD=$VITE_BACKEND_URL_PROD" >> $GITHUB_ENV
        echo "FIREBASE_TOKEN=$FIREBASE_TOKEN" >> $GITHUB_ENV

    - name: Install Dependencies
      run: npm install --force

    - name: Build Vite Project
      run: npm run build

    - name: Deploy to Firebase
      run: firebase deploy --token $FIREBASE_TOKEN --only hosting
